In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [3]:
data = {
    "ClientID": [1, 2, 3, 4, 4],
    "Name": ["Ali", "Sara", "Ahmed", "Zain", "Zain"],
    "Age": [25, 30, None, 28, 28],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Islamabad"],
    "Income": [50000, 60000, 55000, None, 65000],
    "Gender": ["Male", "Female", "Male", "Male", "Male"],
    "Purchase": ["Yes", "No", "Yes", "No", "No"]
}

df = pd.DataFrame(data)

df

   ClientID   Name   Age       City   Income  Gender Purchase
0         1    Ali  25.0    Karachi  50000.0    Male      Yes
1         2   Sara  30.0     Lahore  60000.0  Female       No
2         3  Ahmed   NaN    Karachi  55000.0    Male      Yes
3         4   Zain  28.0  Islamabad      NaN    Male       No
4         4   Zain  28.0  Islamabad  65000.0    Male       No

In [4]:
df = df.drop_duplicates()

df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Income"].fillna(df["Income"].mean(), inplace=True)

df

/tmp/ipykernel_2033/441092047.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/tmp/ipykernel_2033/441092047.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Income"].fillna(df["Income"].mean(), inplace=True)

   ClientID   Name    Age       City   Income  Gender Purchase
0         1    Ali  25.00    Karachi  50000.0    Male      Yes
1         2   Sara  30.00     Lahore  60000.0  Female       No
2         3  Ahmed  27.75    Karachi  55000.0    Male      Yes
3         4   Zain  28.00  Islamabad  57500.0    Male       No
4         4   Zain  28.00  Islamabad  65000.0    Male       No

In [5]:
le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Purchase"] = le.fit_transform(df["Purchase"])

df = pd.get_dummies(df, columns=["City"])

df

,ClientID,Name,Age,Income,Gender,Purchase,City_Islamabad,City_Karachi,City_Lahore
0,1,Ali,25.00,50000.0,1,1,False,True,False
1,2,Sara,30.00,60000.0,0,0,False,False,True
2,3,Ahmed,27.75,55000.0,1,1,False,True,False
3,4,Zain,28.00,57500.0,1,0,True,False,False
4,4,Zain,28.00,65000.0,1,0,True,False,False

In [6]:
scaler = MinMaxScaler()

df[["Age", "Income"]] = scaler.fit_transform(df[["Age", "Income"]])

df

,ClientID,Name,Age,Income,Gender,Purchase,City_Islamabad,City_Karachi,City_Lahore
0,1,Ali,0.00,0.000000,1,1,False,True,False
1,2,Sara,1.00,0.666667,0,0,False,False,True
2,3,Ahmed,0.55,0.333333,1,1,False,True,False
3,4,Zain,0.60,0.500000,1,0,True,False,False
4,4,Zain,0.60,1.000000,1,0,True,False,False

In [7]:
df_final = df.drop(["Name"], axis=1)

df_final

,ClientID,Age,Income,Gender,Purchase,City_Islamabad,City_Karachi,City_Lahore
0,1,0.00,0.000000,1,1,False,True,False
1,2,1.00,0.666667,0,0,False,False,True
2,3,0.55,0.333333,1,1,False,True,False
3,4,0.60,0.500000,1,0,True,False,False
4,4,0.60,1.000000,1,0,True,False,False

In [8]:
df_final.to_csv("cleaned_data.csv", index=False)
print("File saved successfully!")

File saved successfully!